version: '3.8'

services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  backend:
    build: .
    container_name: backend
    volumes:
      - ./backend:/app/backend
    environment:
      - USE_CUDA=false
      - USE_OLLAMA=false
      - USE_CUDA_VER=cu121
      - USE_EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: .
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
    restart: unless-stopped

volumes:
  ollama: {}
